// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTHU_G9-xTkNvfjdV49nknXeNYxdQOXkk',
    appId: '1:637504318289:web:e7594f6a00a0ae59270170',
    messagingSenderId: '637504318289',
    projectId: 'chat-app-7eb01',
    authDomain: 'chat-app-7eb01.firebaseapp.com',
    storageBucket: 'chat-app-7eb01.appspot.com',
    measurementId: 'G-M90DBNX6GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEgEteK3ysnSpE_zh7aN2AhjMfBaqngM',
    appId: '1:637504318289:android:6f07c671ab12d494270170',
    messagingSenderId: '637504318289',
    projectId: 'chat-app-7eb01',
    storageBucket: 'chat-app-7eb01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3arcxquNxoc5PKy7za7Cza19Mhy_XmdE',
    appId: '1:637504318289:ios:a3bc3f64ca05897b270170',
    messagingSenderId: '637504318289',
    projectId: 'chat-app-7eb01',
    storageBucket: 'chat-app-7eb01.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3arcxquNxoc5PKy7za7Cza19Mhy_XmdE',
    appId: '1:637504318289:ios:a3bc3f64ca05897b270170',
    messagingSenderId: '637504318289',
    projectId: 'chat-app-7eb01',
    storageBucket: 'chat-app-7eb01.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTHU_G9-xTkNvfjdV49nknXeNYxdQOXkk',
    appId: '1:637504318289:web:facb8cd65a184a27270170',
    messagingSenderId: '637504318289',
    projectId: 'chat-app-7eb01',
    authDomain: 'chat-app-7eb01.firebaseapp.com',
    storageBucket: 'chat-app-7eb01.appspot.com',
    measurementId: 'G-5NNH6K81P0',
  );
}
